name: tests

on: [push]

jobs:
  test:
    name: Run test with PHP v8.3
    runs-on: ubuntu-latest
    services:
      typesense:
        image: typesense/typesense:26.0
        ports:
          - 8108:8108/tcp
        volumes:
          - /tmp/typesense-server-data:/data
        env:
          TYPESENSE_DATA_DIR: /data
          TYPESENSE_API_KEY: xyz
          TYPESENSE_ENABLE_CORS: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - uses: php-actions/composer@v6
      - run: vendor/bin/phpunit
